# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-23 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sscore', models.IntegerField(blank=True, null=True, verbose_name='\u8003\u8bd5\u6210\u7ee9')),
                ('stype', models.IntegerField(choices=[set([1, '\u5e73\u65f6\u6210\u7ee9']), set([2, '\u671f\u4e2d\u6210\u7ee9']), set([3, '\u671f\u672b\u6210\u7ee9']), set(['\u6a21\u62df\u6210\u7ee9', 4]), set(['\u5176\u4ed6\u6210\u7ee9', 5])], verbose_name='\u8003\u8bd5\u7c7b\u578b')),
                ('sdata', models.CharField(max_length=20, verbose_name='\u8003\u8bd5\u65f6\u95f4')),
                ('scourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_user.CourseInfo', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name_plural': '\u6210\u7ee9\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('snum', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='\u5b66\u53f7')),
                ('sname', models.CharField(max_length=10, verbose_name='\u59d3\u540d')),
                ('ssex', models.IntegerField(choices=[set([1, '\u7537']), set(['\u5973', 2]), set([3, '\u5176\u4ed6'])], verbose_name='\u6027\u522b')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_user.GradeInfo', verbose_name='\u73ed\u7ea7')),
            ],
            options={
                'verbose_name_plural': '\u5b66\u751f\u4fe1\u606f\u8868',
            },
        ),
        migrations.AddField(
            model_name='scoreinfo',
            name='snum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_major.StudentInfo', verbose_name='\u5b66\u53f7'),
        ),
    ]
