# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-01 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_major', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreinfo',
            name='stype',
            field=models.IntegerField(choices=[(1, '\u5e73\u65f6\u6210\u7ee9'), (2, '\u671f\u4e2d\u6210\u7ee9'), (3, '\u671f\u672b\u6210\u7ee9'), (4, '\u6a21\u62df\u6210\u7ee9'), (5, '\u5176\u4ed6\u6210\u7ee9')], verbose_name='\u8003\u8bd5\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='ssex',
            field=models.IntegerField(choices=[(1, '\u7537'), (2, '\u5973'), (3, '\u5176\u4ed6')], verbose_name='\u6027\u522b'),
        ),
    ]
