# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-01 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_major', '0002_auto_20200501_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreinfo',
            name='sdata',
            field=models.DateTimeField(verbose_name='\u8003\u8bd5\u65f6\u95f4'),
        ),
    ]
