# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-08 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_major', '0004_auto_20200501_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreinfo',
            options={'verbose_name': '\u6210\u7ee9\u4fe1\u606f', 'verbose_name_plural': '\u6210\u7ee9\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'verbose_name': '\u5b66\u751f\u4fe1\u606f', 'verbose_name_plural': '\u5b66\u751f\u4fe1\u606f'},
        ),
    ]
