# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-23 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=10, unique=True, verbose_name='\u79d1\u76ee')),
            ],
            options={
                'verbose_name_plural': '\u8bfe\u7a0b\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='GradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clname', models.CharField(max_length=10, unique=True, verbose_name='\u73ed\u7ea7')),
            ],
            options={
                'verbose_name_plural': '\u73ed\u7ea7\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnum', models.CharField(max_length=10, unique=True, verbose_name='\u7f16\u53f7')),
                ('tname', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('tpwd', models.CharField(max_length=60, verbose_name='\u5bc6\u7801')),
                ('tsex', models.BooleanField(default=True, verbose_name='\u7537')),
                ('is_banzhuren', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u73ed\u4e3b\u4efb')),
            ],
            options={
                'verbose_name_plural': '\u6559\u5e08\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='TeachInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_user.CourseInfo', verbose_name='\u6240\u5e26\u8bfe\u7a0b')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_user.GradeInfo', verbose_name='\u6240\u5e26\u73ed\u7ea7')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_user.TeacherInfo', verbose_name='\u6559\u5e08\u59d3\u540d')),
            ],
            options={
                'verbose_name_plural': '\u6559\u5e08\u4efb\u8bfe\u8868',
            },
        ),
    ]
