# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-09 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_user', '0003_auto_20200508_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='tsex',
            field=models.IntegerField(default=1, verbose_name='\u6027\u522b'),
        ),
    ]
