# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-09 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_user', '0004_auto_20200509_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='tsex',
            field=models.IntegerField(choices=[(1, '\u7537'), (2, '\u5973')], default=1, verbose_name='\u6027\u522b'),
        ),
    ]
